# Generated by Django 5.1.6 on 2025-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionlog',
            name='appliance_name',
        ),
        migrations.RemoveField(
            model_name='consumptionlog',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='consumptionlog',
            name='consumption_kwh',
        ),
        migrations.AddField(
            model_name='consumptionlog',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='consumptionlog',
            name='kwp',
            field=models.FloatField(default=0.0, help_text='Kilowatt peak'),
        ),
        migrations.AddField(
            model_name='consumptionlog',
            name='power',
            field=models.FloatField(default=0.0, help_text='Actual power consumption in watts'),
        ),
    ]
